version: "3.8"

services:
  backend:
    build: ./backend
    container_name: viatab-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://admin:password@mongodb:27017/"

  frontend:
    build: ./frontend
    container_name: viatab-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: viatab-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
