name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.13.1
        with:
          minikube version: "v1.30.1"
          kubernetes version: "v1.26.0"
          driver: docker
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable dynamic storage in Minikube
        run: minikube addons enable default-storageclass

      - name: Point Docker to Minikube
        run: |
          echo "::add-mask::$(minikube -p minikube docker-env)"
          eval $(minikube -p minikube docker-env)

      - name: Build images via Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Pre-load MongoDB image # ← optional if you keep imagePullPolicy: Never
        run: docker pull mongo:latest

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Debug dump pod status
        run: |
          echo "=== Pods ==="
          kubectl get pods -o wide
          echo "=== Pod Events ==="
          kubectl describe pods

      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/backend-deployment --timeout=120s
          kubectl rollout status deployment/frontend-deployment --timeout=120s
