name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.13.1
        with:
          minikube version: "v1.30.1"
          kubernetes version: "v1.26.0"
          driver: docker
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Point Docker to Minikube
        run: |
          echo "::add-mask::$(minikube -p minikube docker-env)"
          eval $(minikube -p minikube docker-env)

      - name: Build & load backend image
        run: docker build -t viatab/backend:latest -f backend/Dockerfile backend

      - name: Build & load frontend image
        run: docker build -t viatab/frontend:latest -f frontend/Dockerfile frontend

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/mongodb-pvc.yaml
          kubectl apply -f k8s/mongodb-deployment.yaml
          kubectl apply -f k8s/mongodb-service.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Debug dump pod status
        run: |
          echo "=== Pods ==="
          kubectl get pods -o wide
          echo "=== Deployment Events ==="
          kubectl describe deployment backend-deployment
          echo "=== Backend Logs ==="
          BACKEND_POD=$(kubectl get pods -l app=backend -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $BACKEND_POD --tail=20

      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/backend-deployment --timeout=120s
          kubectl rollout status deployment/frontend-deployment --timeout=120s
